---
# tasks file for ubuntu-ui

- name: Install latest packages
  apt:
    name: "{{ item }}"
    update_cache: yes
    install_recommends: false
  loop:
    - xserver-xorg
    - x11-xserver-utils
    - xinit
    - openbox
    - unclutter
    - xdotool 
    - xserver-xorg-video-fbdev
    - python3-pyinotify

- name: Ensure browser is installed
  apt:
    name: chromium-browser
    state: present

- name: Ensure autologin systemd dir exists
  file:
    path: /etc/systemd/system/getty@tty1.service.d
    state: directory

- name: Enable autologin
  file:
    src: /lib/systemd/system/getty@.service
    dest: /etc/systemd/system/getty.target.wants/getty@tty1.service
    force: true
    state: link
  notify: systemd reload

- name: Configure default systemd target
  file:
    src: /lib/systemd/system/multi-user.target
    dest: /etc/systemd/system/default.target
    state: link
    force: true
  notify: systemd reload

- name: Configure CLI autologin
  template:
    src: autologin.conf.j2
    dest: /etc/systemd/system/getty@tty1.service.d/autologin.conf
  notify: systemd reload

- name: Configure openbox
  template:
    src: openbox.j2
    dest: /etc/xdg/openbox/autostart

- name: Make sure we have a 'wheel' group
  group:
    name: wheel
    state: present

- name: Allow 'wheel' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'

- name: Adding existing user '{{ kiosk_user }}' to group tty, wheel
  user: name='{{ kiosk_user }}'
        groups=tty,wheel,docker
        append=yes

- name: Set autostart on boot in bash_profile
  template:
    src: bash_profile.j2
    dest: /home/{{ kiosk_user }}/.bash_profile
    owner: 1000
    group: 1000

- name: Install a autopoweroff package from the github
  apt:
    deb: https://github.com/deragon/autopoweroff/releases/download/4.0.0/autopoweroff_4.0.0_all.deb
  notify:
   - restart device